const tailwindBaseKeys = {
	align: '',
	alignContent: '',
	alignItems: '',
	alignSelf: '',
	animation: '',
	appearance: '',
	aspect: '',
	bgBlur: '',
	bgAttachment: '',
	bgClip: '',
	bgColor: '',
	bgImage: '',
	bgOrigin: '',
	bgOpacity: '',
	bgPosition: '',
	bgRepeat: '',
	bgSize: '',
	borderCollapse: '',
	border: '',
	borderColor: '',
	borderOpacity: '',
	borderRadius: '',
	borderSpacing: '',
	borderStyle: '',
	borderWidth: '',
	bottom: '',
	basis: '',
	color: '',
	columns: '',
	cursor: '',
	display: '',
	divide: '',
	divideColor: '',
	divideOpacity: '',
	divideStyle: '',
	divideWidth: '',
	duration: '',
	fade: '',
	focus: '',
	fontFamily: '',
	fontSize: '',
	fontStyle: '',
	fontWeight: '',
	fontVariant: '',
	flex: '',
	flexDirection: '',
	flexWrap: '',
	fill: '',
	forcedColorAdjust: '',
	grid: '',
	gridColumn: '',
	gridCols: '',
	gridFlow: '',
	gridRow: '',
	gridRows: '',
	group: '',
	grow: '',
	height: '',
	hover: '',
	items: '',
	inset: '',
	justify: '',
	justifyContent: '',
	justifyItems: '',
	justifySelf: '',
	leading: '',
	left: '',
	lineClamp: '',
	listImg: '',
	listPosition: '',
	listStyle: '',
	location: '',
	margin: '',
	maxHeight: '',
	maxWidth: '',
	minHeight: '',
	minWidth: '',
	objectFit: '',
	objectPosition: '',
	opacity: '',
	origin: '',
	outline: '',
	outlineColor: '',
	outlineOffset: '',
	outlineStyle: '',
	outlineWidth: '',
	overflow: '',
	overflowWrap: '',
	padding: '',
	path: '',
	placeholderColor: '',
	placeContent: '',
	placeItems: '',
	placeSelf: '',
	pointerEvents: '',
	position: '',
	ring: '',
	ringColor: '',
	ringOffset: '',
	ringOffsetColor: '',
	resize: '',
	right: '',
	rotate: '',
	scale: '',
	shadow: '',
	shadowColor: '',
	shrink: '',
	size: '',
	space: '',
	spacing: '',
	stroke: '',
	strokeWidth: '',
	tableLayout: '',
	textAlign: '',
	textColor: '',
	textDecoration: '',
	textOverflow: '',
	textTransform: '',
	textWrap: '',
	top: '',
	tracking: '',
	transform: '',
	transition: '',
	translate: '',
	touchAction: '',
	userSelect: '',
	visibility: '',
	willChange: '',
	weight: '',
	whitespace: '',
	width: '',
	wordBreak: '',
	zIndex: '',
	variants: '',
	tailwind: '',
};

const tailwindContainerKeys = {
	center: '',
	gutters: '',
};

const tailwindGridKeys = {
	cols: '',
	rows: '',
	flow: '',
	gap: '',
	autoCols: '',
	autoRows: '',
};

const tailwindColKeys = {
	sm: '',
	md: '',
	lg: '',
	xl: '',
	xxl: '',
	span: '',
	order: '',
};

export const tailwindKeys = {
	...tailwindBaseKeys,
	...tailwindContainerKeys,
	...tailwindGridKeys,
	...tailwindColKeys,
};
