const tailwindBaseKeys = {
	align: '',
	animation: '',
	aspect: '',
	bgBlur: '',
	bgClip: '',
	bgColor: '',
	bgImage: '',
	bgOpacity: '',
	bgPosition: '',
	bgSize: '',
	border: '',
	borderColor: '',
	borderOpacity: '',
	borderRadius: '',
	borderStyle: '',
	bottom: '',
	color: '',
	cursor: '',
	display: '',
	divide: '',
	divideColor: '',
	divideOpacity: '',
	duration: '',
	fade: '',
	focus: '',
	fontFamily: '',
	fontSize: '',
	fontStyle: '',
	fontWeight: '',
	fontVariant: '',
	flex: '',
	grid: '',
	gridFlow: '',
	group: '',
	height: '',
	hover: '',
	items: '',
	inset: '',
	justify: '',
	leading: '',
	left: '',
	lineClamp: '',
	listImg: '',
	listPosition: '',
	listStyle: '',
	location: '',
	margin: '',
	maxHeight: '',
	minHeight: '',
	opacity: '',
	origin: '',
	outline: '',
	outlineColor: '',
	outlineOffset: '',
	overflow: '',
	padding: '',
	path: '',
	placeholderColor: '',
	pointerEvents: '',
	position: '',
	ring: '',
	ringColor: '',
	ringOffset: '',
	ringOffsetColor: '',
	right: '',
	rotate: '',
	scale: '',
	shadow: '',
	shadowColor: '',
	size: '',
	space: '',
	spacing: '',
	stroke: '',
	textDecoration: '',
	textTransform: '',
	top: '',
	tracking: '',
	transform: '',
	transition: '',
	translate: '',
	weight: '',
	whitespace: '',
	width: '',
	zIndex: '',
	variants: '',
	tailwind: '',
};

const tailwindContainerKeys = {
	center: '',
	gutters: '',
};

const tailwindGridKeys = {
	cols: '',
	rows: '',
	flow: '',
	gap: '',
};

const tailwindColKeys = {
	sm: '',
	md: '',
	lg: '',
	xl: '',
	xxl: '',
	span: '',
	order: '',
};

export const tailwindKeys = {
	...tailwindBaseKeys,
	...tailwindContainerKeys,
	...tailwindGridKeys,
	...tailwindColKeys,
};
